### PR TITLE
fix: render missing properties in html

### LINKED ISSUE #39: [BUG] Supplementary Information C04-C09 not rendered in HTML
**Describe the bug**
The section `SupplementaryInformation` with the fields `C04-C09` are not rendered in HTML.

**To Reproduce**
1. Compare the HTML and PDF rendering of `test/fixtures/valid_certificate_4.json`.

**Expected behavior**
Supplementary information is rendered on HTML the same way as on PDF.

### PR DESCRIPTION
**Pull request by eamon0989**
# Description

This PR fixes an issue where some properties are not rendered correctly in the html.
Add section to render missing properties in `template.hbs`.
Update html fixtures.
Update @s1seven dependencies.
Add `set-local-paths` script.
Set a local path in `partials-map.json` for `inspection` to allow the tests to pass, which will be updated during the release process.
Update CI workflow to update `inspection` path to a local path before running tests.
Update `update-version` script to update remote partials before generating html fixtures, and to update local partials after so that they generate correctly.
Add `RefSchemaUrl` definition.
Increase PDF generation test timeout value.
Update `generate-pdf.min.js` and update PDF fixtures.

Fixes #39 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] ⚠️ I ensured that the changes to the schema will be compatible with [schema-tools library](https://github.com/s1seven/schema-tools)

### CODE REVIEW

File: utils/set-local-paths.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+}
+
+(async function () {
+  try {
+    const { filePath, properties } = localPartialsMapPaths;
+    const partialsMap = await loadExternalFile(filePath, 'json', false);
+
+    let partialsMapHasChanged = false;
+    for (const { value, path } of properties) {
+      if (typeof get(partialsMap, path, undefined) === 'string') {
```
Comment (getlarge) [inline utils/set-local-paths.js:20]: shouldn't `(get(partialsMap, path, undefined))` be enough ?

**Review by getlarge — CHANGES_REQUESTED** [review]
Can you add a short remark in the README indicating that `npm run set-local-paths` should be called to use local handlebars partials for HTML rendering ?

**Review by getlarge — APPROVED** [review]
